version: '2'
services:
 apps:
     build: ./docker-files/app
     env_file: .env
     privileged: true
     container_name: ${PROJECTNAME}-${JOB_BASE_NAME}-app
     hostname: ${PROJECTNAME}${JOB_BASE_NAME}
     mem_limit: "1G"
     memswap_limit: "1G"
     image: teravisiontech/${PROJECTNAME}
     ports:
           - "${HTTPPORT}:80"
     restart: always
     environment:
       DATABASE: ${ENVIRONMENT}
       DB_USER: ${ENVIRONMENT}
       DB_PASSWORD: ${ENVIRONMENT}
       TERM: xterm
     volumes:
       - "/home/ubuntu/Workspace/mrpresta-wiki/projects:/var/www/html"
